stages:
  split:
    cmd: mlflow run src/splitting -e split-data --experiment-name=${train.experiment_name}
    params:
      - split.root
      - split.output
      - split.train_percentage
      - split.val_percentage
      - split.random_state
    deps:
      - ${split.root}
      - src/splitting
    outs:
      - ${split.output}

  preprocess:
    foreach:
      - ${preprocess.train}
      - ${preprocess.val}
      - ${preprocess.test}
    do:
      cmd: mlflow run src/preprocessing -e preprocess-data --experiment-name=${train.experiment_name} -P phase=${item} -P input_path=${split.output} -P output=${preprocess.output_dir}
      deps:
        - ${split.output}/${item}
        - src/preprocessing
      outs:
        - ${preprocess.output_dir}/${item}

  train:
    cmd: mlflow run src/training -e train-classifier --experiment-name=${train.experiment_name} -P experiment_name=${train.experiment_name} -P train=${preprocess.output_dir}/train -P val=${preprocess.output_dir}/val -P model_path=${train.model_path} -P model_name=${train.model_name} -P num_epochs=${train.num_epochs} -P batch_size=${train.batch_size} -P learning_rate=${train.learning_rate}
    deps:
      - ${preprocess.output_dir}/train
      - ${preprocess.output_dir}/val
      - src/training

  evaluate:
    cmd: mlflow run src/evaluation -e evaluate-model 
    params:
      - evaluate.environment_name
      - ${preprocess.output_dir}/test
      - ${train.model_path}
    deps:
      - ${train.model_path}
      - ${preprocess.output_dir}/test
      - src/evaluation
