name: pokemon-classifier
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow
    - opentelemetry-api
    - opentelemetry-sdk
    - opentelemetry-exporter-otlp-proto
    - opentelemetry-instrumentation
    - opentelemetry-instrumentation-requests
    - torch
    - torchvision
    - torchmetrics
